### ISSUE TITLE
Allow Helm release to be named directly

### ISSUE THREAD

**Issue by thectrltab** [cloudposse/terraform-aws-helm-release#22]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Sometimes it can be useful to set the Helm version name directly without using the context name. It could also be useful to avoid duplication in IAM policy and role names.

## Expected Behavior

Allow the Helm version to be named directly without having to overwrite the context name.

## Use Case

I need to deploy two releases of the same Helm chart (external-dns) with different names, for example: _external-dns-public_ and _external-dns-private_, but using the same context (environment, stage and name).

## Describe Ideal Solution

Create a new variable `release_name`. When set it will overwrite the name of the context and the name of the chart.

**Comment by nitrocode** [comment]
Why not pass in the context and overwrite the name?

```
module "external_dns_private" {
  name = "private"

  context = module.this.context
}

module "external_dns_public" {
  name = "public"

  context = module.this.context
}
```

**Comment by nitrocode** [comment]
@thectrltab can you try the above solution? if it doesn't work for you, please re-open this ticket.

**Comment by thectrltab** [comment]
@nitrocode Thanks for your answer.
That solution doesn't work for me since I can't call releases only as "public" or "private".

If I give it the following name "external-dns-private". The IAM Role name is too long.

I would like to be able to give a name to the release without affecting the IAM roles (context.name): 
https://github.com/cloudposse/terraform-aws-eks-iam-role/blob/master/main.tf#L8-L11

**Comment by nitrocode** [comment]
Ah ok, then let's keep this open and when time permits we can create a pr

**Comment by nitrocode** [comment]
@thectrltab can you try out the module using the feature branch of the pr and see if that works for you?

**Comment by thectrltab** [comment]
@nitrocode Yes, it works perfectly. Thanks for your time.

**Comment by nitrocode** [comment]
Released in version https://github.com/cloudposse/terraform-aws-helm-release/releases/tag/0.4.3
