### ISSUE TITLE
Create an IRSA without an IAM policy

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-helm-release#37]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
You may want an IRSA for best practices without an IAM policy to further reduce blast radius so you can have a pod not use the eks node worker role by default.

If you enable an iam role without supplying policy statements, you receive this bug

```hcl
╷
│ Error: creating IAM Policy
|
| MalformedPolicyDocument: Syntax errors in policy.
│ 
│   with module.datadog_agent.module.eks_iam_role.aws_iam_policy.service_account[0],
│   on .terraform/modules/datadog_agent.eks_iam_role/main.tf line 85, in resource "aws_iam_policy" "service_account":
│   85: resource "aws_iam_policy" "service_account" {
```

## Expected Behavior
Enable the IAM role without creating an iam policy resource

## Additional context
This may need to be added directly into the upstream module and then bumped here

- https://github.com/cloudposse/terraform-aws-iam-policy/issues/23

**Comment by Nuru** [comment]
Closing as `wontfix` because you can always supply a policy, even if it is

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

**Comment by dennislapchenko** [comment]
@Nuru Why does one need to provide this Deny policy if this can be solved simply with a `iam_policy_enabled` and pass it down to iam_policy module?
